version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: meu_banco
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwordTeste
      POSTGRES_DB: tarefas
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  quarkus_dev:
    image: maven:3.8.6-openjdk-18
    container_name: quarkus_dev
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      QUARKUS_LAUNCH_DEVMODE: "true"
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/tarefas
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: passwordTeste
      QUARKUS_HTTP_PORT: 8080
    command: ["mvn", "quarkus:dev"]

volumes:
  pg_data:
